version: "3"
services: 

    webserver:
      image: nginx:alpine
      container_name: api-gateway
      working_dir: /www
      volumes:
          - ./www:/www 
          - ./docker/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      networks:
            gateway_net:
                ipv4_address: 172.28.1.2 

networks:
    gateway_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16


